### PR TITLE
Added get_device_by_id to the device_manager and example

### PR DESCRIPTION
**Pull request by iteroji**
Added a convenience method to get a device by its identifier. This is most useful if you have multiple USB or network devices attached and want to work with a specific one without having to enumerate all and find the one by id. 

Created a simple example that demonstrates the usage of the `get_device_by_type` and `get_device_by_id` methods.

### CODE REVIEW

**Review by s1341 — APPROVED** [review]

**Comment by s1341** [comment]
@iteroji please see the CI error. The test cannot be run on CI.

**Comment by iteroji** [comment]
> @iteroji please see the CI error. The test cannot be run on CI.

I had invalid characters in rust doc causing doc test to fail. Updated it, now all tests should pass

**Comment by s1341** [comment]
Needs a `cargo fmt`.

**Comment by s1341** [comment]
And now clippy is complaining :(

**Comment by iteroji** [comment]
> And now clippy is complaining :(

At least now I know what checks to run before PR :)

**Comment by s1341** [comment]
Thanks!

**Pull request merged**
