### PR TITLE
Updated to frida 16

### PR DESCRIPTION
**Pull request by domenukk**
Frida 16 is out 🎉

### CODE REVIEW

**Comment by domenukk** [comment]
Oops, `cargo test --features auto-download --features invocation-listener` leads to a segfault, did the api change?

**Comment by domenukk** [comment]
Ok might be related to missing symbols(?)
At least, linking fails on Linux, with errors similar to the ones in #57

**Comment by oleavr** [comment]
@domenukk Yay! These regressions are finally fixed as of 16.0.2, released last night 🙌

**Comment by meme** [comment]
Thanks!

**Pull request closed without merging**
