### PR TITLE
Update frida devkits to 15.1.14

### PR DESCRIPTION
**Pull request by s1341**

### CODE REVIEW

**Review by meme — APPROVED** [review]
LGTM. Why is `link-cplusplus` necessary? We have not needed it in the past?

**Comment by s1341** [comment]
We need to link with `libc++`/`libstdc++` as the gum devkit now requires that.

**Comment by s1341** [comment]
Please cut a release when you have merged.

**Comment by oleavr** [comment]
I'm so sorry. This is a terrible regression in Stalker on x86/x86_64. Will be fixed in the next release.

**Comment by s1341** [comment]
So we should wait?

**Comment by meme** [comment]
As 15.1.16 is released I think we can reopen this. Otherwise I can close it and update it in master.

**Comment by meme** [comment]
Done in v0.6.4

**Pull request closed without merging**
