### PR TITLE
Linux Arm/Arm64 support

### PR DESCRIPTION
**Pull request by WorksButNotTested**
Added a github workflow for ARM and the necessary minimal fixes to make it build. Note that there is only a template implementation of the `ArmInstructionWriter` and `ArmRelocator` for now. But they can be filled out at a later date as required. Also added a test-runner for aarch64.

### CODE REVIEW

**Comment by WorksButNotTested** [comment]
```
(gdb) r
Starting program: /home/jon/frida_sys-4a7ee9448b1f259c 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
free(): invalid pointer

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000007fb7d4faac in __GI_abort () at abort.c:79
#2  0x0000007fb7d9cf40 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb7e5e518 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x0000007fb7da4344 in malloc_printerr (str=str@entry=0x7fb7e59fb8 "free(): invalid pointer") at malloc.c:5347
#4  0x0000007fb7da5b88 in _int_free (av=0x7fb7e9da98 <main_arena>, p=0x5555689440, have_lock=<optimized out>) at malloc.c:4173
#5  0x000000555556e4e8 in g_private_replace (key=0x55556652a8 <module_error_private>, value=0x0) at ../../../deps/glib/glib/gthread-posix.c:1232
#6  0x000000555558465c in g_module_set_error_unduped (error=<optimized out>) at ../../../deps/glib/gmodule/gmodule.c:297
#7  0x0000005555584680 in g_module_set_error (error=error@entry=0x0) at ../../../deps/glib/gmodule/gmodule.c:304
#8  0x000000555558482c in g_module_symbol (module=0x555568b130, symbol_name=0x5555624cf4 "soup_uri_new", symbol=0x7ffffff258) at ../../../deps/glib/gmodule/gmodule.c:889
#9  0x000000555556b4c4 in soup2_is_loaded () at ../../../deps/libsoup/libsoup/soup-init.c:30
#10 soup_init () at ../../../deps/libsoup/libsoup/soup-init.c:54
#11 soup_init_ctor () at ../../../deps/libsoup/libsoup/soup-init.c:96
#12 0x0000005555616078 in __libc_csu_init ()
#13 0x0000007fb7d4fdb8 in __libc_start_main (main=0x555556b724 <main>, argc=1, argv=0x7ffffff3f8, init=0x5555616018 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>)
    at ../csu/libc-start.c:264
#14 0x000000555556b554 in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by WorksButNotTested** [comment]
It seems that running the tests for `frida` (core) and `frida-gum` separately (e.g. cd frida-gum && cargo test ...) means that they succeed (as done by the other jobs), performing a `cargo test` from the top-level however does not. Although it seems unlikely that someone would use by the `core` and `gum` devkits in the same application.

**Comment by WorksButNotTested** [comment]
Looks like it's all green. Sorry for all the tweaks. I've been using `act` to try to run the workflow actions locally, but its not super representative.

**Comment by meme** [comment]
Thanks. I have a few thoughts. I feel like the attribute flags we have now in this file are getting out of hand. Would it make sense to have a separate file for each architecture and then this main instruction writer file conditionally includes each of the 4 files (x86, x86_64, arm, aarch64)?

Secondly, I can't say I'm thrilled about running QEMU in CI to test aarch64. I will discuss with Ole if there are other options, like having runners for Frida for the ARM architecture.

**Comment by WorksButNotTested** [comment]
That’s makes sense. Worth having separate files just because the original file is getting so long! That should be a fairly easy fix.

qemu-user isn’t totally representative as a test environment, so if there is a way to get things working with a native environment, then that should be preferred.

What’s the best way forward? Is it easier for you to make the tweaks? Or would you like me to make some changes? It’ll likely be the new year before I get some time and I totally understand if that’s the case for you too. There’s no huge rush, but it would be good to get things working on a couple more architectures!

**Comment by meme** [comment]
> qemu-user isn’t totally representative as a test environment, so if there is a way to get things working with a native environment, then that should be preferred.

That's the plan. We'll see.

> What’s the best way forward? Is it easier for you to make the tweaks?

I will take over, but it will be in the new year. Unless there is a specific rush I think this is acceptable. Thanks again for the patch.

**Comment by WorksButNotTested** [comment]
Awesome. Thanks for taking this forward. In the new year is absolutely fine. I certainly wouldn’t expect to be dictating anyone else schedule in any case!

**Comment by WorksButNotTested** [comment]
I've reworked this commit to split the different architectures into separate files as suggested. It's made the files a much more manageable size and greatly reduced all of the conditional compilation.

I don't think that `frida-gum` has CI for `linux-arm` or `linux-arm64` (only macos and android for ARM architecture), so I don't know if it is possible to run the tests on a native environment using github actions. Therefore I have split the PR into two separate commits so that the ARM functionality can be merged even if the CI approach is undesireable for now.

**Comment by meme** [comment]
I've chosen not to use the GitHub workflow for now. We can revisit the CI later once I have some other options. For now, I have removed it and squashed and merged it. Thank you for the contribution.

**Comment by WorksButNotTested** [comment]
Awesome. Thanks very much for the merge!

**Pull request closed without merging**
