### PR TITLE
Update frida, fix bindings, add testcases

### PR DESCRIPTION
**Pull request by domenukk**
This PR runs tests for Frida Gum.
It also fixes some bugs found during tests, and updates the frida version to latest.

### CODE REVIEW

**Comment by domenukk** [comment]
Couldn't get Windows to find libclang, maybe someone with more Github CI experience could help out. Should be fine for now, though.

**Review by meme — COMMENTED** [review]
I'm a bit confused with the GitHub Actions update, we already run tests here: https://github.com/frida/frida-rust/blob/master/.github/workflows/build.yml#L25-L27. What is the purpose of the changes to the workflow? If it's just to enable all features, can we just add that to my existing "test" step?

Other than that LGTM. Thanks.

**Comment by domenukk** [comment]
They are just Ubuntu latest, my goal was to add more operating systems with these tests.
For some reason, I can't get windows to build, sadly, so it's less useful..
So I can merge it if you want

**Comment by meme** [comment]
It looks like bindgen themselves use AppVeyor rather than GitHub Actions. Do you want to give that a try? https://github.com/rust-lang/rust-bindgen/blob/de94b4875659fb76b4ae21ee4f677a344ff8a1ca/appveyor.yml

Otherwise, I am OK to merge as-is. Thanks.

**Comment by domenukk** [comment]
Updated to the latest frida version, everything still seems to work.
For AppVeyor, we'd need an account with them, which I can't really create. Also I think it makes more sense to wait for Github to fix their system than to switch CI systems, but up to you.
In any case, maybe merge this now to fix windows builds and maybe fix ci later?

**Comment by meme** [comment]
Sounds good. FYI you have to update https://github.com/frida/frida-rust/blob/master/frida-gum-sys/FRIDA_VERSION and https://github.com/frida/frida-rust/blob/master/frida-sys/FRIDA_VERSION as well. These used to be a symlink but apparently that broke windows so we had to duplicate the files.

Once those are updated, we can merge & make a release. Thanks

**Comment by meme** [comment]
Unfortunately not ☹️ . I am open to suggestions, but referencing files out-of-crate will not work. And we can't use symlinks because on Windows it just makes a file with the contents of a relative path to the file, rather than a link to the original file.

**Comment by domenukk** [comment]
In theory the version number could be exported by one of the crates, the other ones can include that crate in their build.rs

**Comment by meme** [comment]
Sure, we could move the FRIDA_VERSION file into frida-build and then export it as a variable from there with include_bytes! and then use it in the frida-sys and frida-gum-sys crates which already have frida-build file as a dependency.

Might be best if that is a separate PR, if you don't mind just updating all 3 for now so we can merge this.

**Comment by domenukk** [comment]
all right give me a sec

**Comment by domenukk** [comment]
Just out of curiosity, does frida-core.h eventually need to be updated if we increase the versions?

**Comment by meme** [comment]
It's used only for `cargo check` on docs.rs since it does not have network access but bindgen still needs a header to run. I can update it afterwards so this is good as-is.

Thanks!

**Review by meme — APPROVED** [review]

**Pull request merged**
