### PR TITLE
bump frida version to 16.2.5

### PR DESCRIPTION
**Pull request by aviramha**

### CODE REVIEW

**Comment by s1341** [comment]
Can you get CI green please, then I will merge.

**Comment by aviramha** [comment]
CI seems to fail regardless of my changes and I'm not sure how to fix it?

**Comment by s1341** [comment]
Looks like this is the issue: https://github.com/rust-lang/cargo/issues/13875

Can you please rename `doc_cfg` to `docsrs` throughout. I prefer to merge when green.

**Comment by s1341** [comment]
woot! Thanks!

**Pull request merged**
