### PR TITLE
frida-gum: dereference listener objects

### PR DESCRIPTION
**Pull request by ajwerner**
When combined with https://github.com/frida/frida-rust/pull/153, fixes https://github.com/frida/frida-rust/issues/152.

### CODE REVIEW

**Comment by s1341** [comment]
This means that you need to keep references to the returned `Listener`s alive for as long as you want the hooks to remain, right? That will break a lot of stuff.

**Comment by ajwerner** [comment]
No Frida increments the ref count when you attach and drops it when you detach. That’s why it was a leak.

**Comment by s1341** [comment]
Ok. Let's see what CI says.

**Comment by s1341** [comment]
Merged. Thanks!

**Pull request merged**
