### PR TITLE
Add a couple of useful features to Device

### PR DESCRIPTION
**Pull request by fabianfreyer**
I needed these things, so here they are. If you'd rather have self-contained PR's, happy to do that too,.

- Get a device's connection type (Local/Remote/USB).
- Get a device's system properties (e.g. os version, jailed/full access, interface list, UDID,...)
- Spawn a process on a device. Compared to the implementation in #101, this allows setting SpawnOptions.
- Kill a process on a device

Would be really cool to get these into a 0.14 release!

### CODE REVIEW

**Comment by fabianfreyer** [comment]
[46d9dda](https://github.com/frida/frida-rust/pull/110/commits/46d9dda0e218684536ce7d1eaf3f5f6e96fe801a) will probably conflict with #108, so whichever gets merged last should use the other's `DeviceType` struct.

**Comment by meme** [comment]
LGTM. Please look into the Windows build failures.

**Comment by fabianfreyer** [comment]
@meme done, and rebased.

**Comment by fabianfreyer** [comment]
> Please resolve the conflicts so I can merge. Thanks again, apologies for the delay.

done. I've merged my DeviceType implementations into @csnewman's (#108), in an AFACT backwards-compatible way.

**Comment by fabianfreyer** [comment]
Oh, looks like I didn't run rustfmt on each commit. Fixed that, sorry!

**Review by meme — APPROVED** [review]

**Comment by fabianfreyer** [comment]
Thanks!

**Pull request merged**
