### PR TITLE
remove external capstone dependency, use frida's

### PR DESCRIPTION
**Pull request by aviramha**

### CODE REVIEW

**Comment by aviramha** [comment]
Closes #81

**Comment by aviramha** [comment]
@meme would love your review :)

**Comment by meme** [comment]
I don't object to these changes, but the problem is for more performance-intensive programs like fuzzers, they need a separate decode stage. The other option is to have a Frida fork of Capstone, but that has its own challenges (especially since Frida's Capstone and the regular Capstone crate can't co-exist).

So, if @domenukk and @s1341 don't object to these changes (specially the potential performance impact), then that's OK with me - we can shed the dependency and the complexity.

**Comment by s1341** [comment]
I think we can live with this. So far as I know, we have been until now. My only hesitation is that tools using `frida-gum` and `capstone-rs`, like LibAFL does, will need to re-decode the instructions during stalking.

**Comment by meme** [comment]
Let's roll with this. Thank you.

**Review by meme — APPROVED** [review]

**Pull request merged**
