### PR TITLE
bump frida version to 16.5.1

### PR DESCRIPTION
**Pull request by aviramha**

### CODE REVIEW

**Comment by aviramha** [comment]
can someone re-run? seems it hit a timeout for some reason

**Comment by s1341** [comment]
@aviramha I reran and it still fails... Can you verify that there isn't an issue?

**Comment by aviramha** [comment]
that would be an issue with frida itself then, as I only bumped the version ⭕ 
I can't run it locally (running on macOS) so can't debug too much

**Comment by s1341** [comment]
I ran locally and the tests passed... Weird. I'm going to rerun again.

**Comment by aviramha** [comment]
looked a bit further - There are no tests in said files
test frida/src/injector.rs - injector::Inject (line 94) - compile ... ok
test frida/src/injector.rs - injector::Inject (line 74) ... ok
test frida/src/script.rs - script::Script<'a>::handle_message (line 184) ... ok
test frida/src/device.rs - device::Device<'a>::get_type (line 47) has been running for over 60 seconds
test frida/src/device.rs - device::Device<'a>::query_system_parameters (line 61) has been running for over 60 seconds

and the only place where I see those files being tested, are on x86_64 for some reason? :|

**Comment by s1341** [comment]
It seems it is using the examples in the comments as tests.... Any idea why?

**Comment by aviramha** [comment]
I think I found out why. Not sure why it started now though.

**Comment by s1341** [comment]
Ok. Nice!

**Pull request merged**
