### PR TITLE
Add support for stalker-observer

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by meme** [comment]
LGTM. Please address the lints from CI.

**Comment by WorksButNotTested** [comment]
Thanks for the quick feedback. I don’t think the lints relate to any files I have changed, so not sure how they’ve cropped up? Happy to tackle them, but just wary of breaking something without understanding what’s going on.

**Comment by WorksButNotTested** [comment]
Just ran a `cargo clippy --fix -F auto-download` and everything seems happy?!

**Comment by WorksButNotTested** [comment]
Seems that the `as` statements are necessary for x86. But are redundant on x64. Given how many there are, it would introduce a large number of conditional `#[cfg(...)] ` blocks? What do you think is the best approach?

**Comment by meme** [comment]
Ah. In that case, it's noise. Please disable that lint for x64 for that file.

**Comment by WorksButNotTested** [comment]
Hopefully this should sort it. There is the converse issue for `x86` where clippy complains about `u32`->`u32` casts. So I disabled the rule for both architectures.

**Review by meme — APPROVED** [review]

**Comment by WorksButNotTested** [comment]
Awesome, thanks for the merge.

**Pull request merged**
