### PR TITLE
Add Injector

### PR DESCRIPTION
**Pull request by fabianfreyer**

### CODE REVIEW

**Comment by meme** [comment]
Thanks for the contribution. Please take a look at the CI errors

**Comment by fabianfreyer** [comment]
@meme I hope I addressed the failed CI errors. It seems like on apple and windows there is no `_frida_` prefix before external symbols in the devkit, but on other platforms there is. I hope I caught all those, but can't trigger a CI run on my own.

**Comment by meme** [comment]
Instead of handing the symbol naming within the `frida` crate, can you move your conditional imports into conditional exports in the `frida-sys` crate?

This is what we do for the `frida-gum-sys` crate: https://github.com/frida/frida-rust/blob/main/frida-gum-sys/src/lib.rs#L19-L25

**Comment by fabianfreyer** [comment]
Done. Also, consolidated the existing exports into a single `pub use crate::{...}` statement, hope that's fine.

**Review by meme — APPROVED** [review]

**Pull request merged**
