### PR TITLE
Changes to support 32-bit

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by meme** [comment]
Have you seen https://github.com/frida/frida-rust/pull/64, it seems that these changes should be incorporated together?

**Comment by WorksButNotTested** [comment]
Oh cool. Looks like my PR and the other one are both pretty similar. I’m not precious about my code, just need 32-but support working for my use case, so happy with whatever approach you think best.

CI should be a case of just passing the architecture triple to cargo when building and downloading the x86 rather than x64 versions of the devkits.

**Comment by WorksButNotTested** [comment]
Here's an update. I've added CI for x86 too. Both for the checks as well as for testing `frida-gum` and `frida-core`. I think github has refused to run it though since I have obviously updated the workflow (so I think maybe it needs approving first). But, it seems to work...
https://github.com/WorksButNotTested/frida-rust/actions/runs/3464049073/

**Review by meme — APPROVED** [review]

**Comment by WorksButNotTested** [comment]
Awesome. Thanks for the merge!

**Comment by meme** [comment]
Thanks!

**Pull request merged**
