### PR TITLE
fix: compilation on nightly

### PR DESCRIPTION
**Pull request by amaanq**
It does not compile on nightly (`1.79.0-nightly (805813650 2024-03-31)` to be exact) due to the `#![deny(warnings)]` attribute and redundant imports becoming a warning. Thanks!

### CODE REVIEW

**Comment by s1341** [comment]
Looks like it needs a little work. Please fix CI and then I will land.

**Comment by amaanq** [comment]
oops, fixed

**Comment by amaanq** [comment]
Hey @s1341 gentle reminder in case you're busy/forgot about this pr :)

**Comment by s1341** [comment]
Thanks for your contribution!

**Comment by amaanq** [comment]
thanks!

**Pull request merged**
